In [28]:
import numpy as np

Crie um array com 4 linhas e 3 colunas comvalores aleatórios.

In [29]:
np.random.random((4,3))

array([[0.97083609, 0.08200066, 0.29169355],
       [0.83808514, 0.98590297, 0.14652859],
       [0.35959962, 0.74937971, 0.27287949],
       [0.28008747, 0.75206756, 0.83232723]])

Crie um Array com 5 colunas e 10 linhas inicializados com zeros.

In [30]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Crie um array com valores inteiros 3 linhas e 5 colunas com valores aleatorios.

In [31]:
np.random.randint(30,size=(3,5))

array([[15, 24, 21,  6, 15],
       [13, 28, 20, 21,  8],
       [19, 22, 13,  6, 22]])

### Crie um Array com 3 dimensões

In [32]:
arr1_2d = np.array([[1, 2], [3,4]]) 
arr2_2d = np.array([[5, 6], [7,8]]) 
arr3_2d = np.array([[9, 2], [3,4]]) 

arr_3d = np.array([arr1_2d, arr2_2d,arr3_2d])

In [33]:
arr1_2d

array([[1, 2],
       [3, 4]])

In [34]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [35]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

#### Crie um array que irá representar a cartilha de um bingo. Os numeros das suas cartelas variam entre 1 e 30, e vorcê terá 10 participantes. Cada cartela terá 12 números (4,3)

In [36]:
bingo = np.random.randint(1, 31, size=(10,4,3))
bingo


array([[[24, 12, 19],
        [ 5, 15,  7],
        [ 7, 21, 20],
        [ 1, 22, 17]],

       [[10,  3, 30],
        [20,  5, 18],
        [ 8, 16, 16],
        [22, 29, 30]],

       [[30, 29, 23],
        [ 1, 15, 20],
        [25,  6, 25],
        [ 6,  7, 20]],

       [[17, 26, 15],
        [24, 28, 10],
        [15, 28,  4],
        [11, 27, 21]],

       [[23, 21,  4],
        [ 6, 25,  8],
        [ 4,  9,  1],
        [28, 16, 16]],

       [[27, 15, 10],
        [11,  7, 25],
        [11, 27, 25],
        [25, 10, 13]],

       [[26, 23, 30],
        [14, 18, 11],
        [30, 10,  8],
        [ 1,  1,  7]],

       [[12, 20,  5],
        [26, 10, 19],
        [14, 22, 24],
        [30, 16, 19]],

       [[ 4, 27,  4],
        [ 4, 17,  2],
        [29, 17,  2],
        [29,  8, 11]],

       [[17, 28, 13],
        [15, 29, 20],
        [28,  7,  9],
        [16, 28, 19]]])

#### Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas

In [37]:
bingo.reshape((5,4,6))

array([[[24, 12, 19,  5, 15,  7],
        [ 7, 21, 20,  1, 22, 17],
        [10,  3, 30, 20,  5, 18],
        [ 8, 16, 16, 22, 29, 30]],

       [[30, 29, 23,  1, 15, 20],
        [25,  6, 25,  6,  7, 20],
        [17, 26, 15, 24, 28, 10],
        [15, 28,  4, 11, 27, 21]],

       [[23, 21,  4,  6, 25,  8],
        [ 4,  9,  1, 28, 16, 16],
        [27, 15, 10, 11,  7, 25],
        [11, 27, 25, 25, 10, 13]],

       [[26, 23, 30, 14, 18, 11],
        [30, 10,  8,  1,  1,  7],
        [12, 20,  5, 26, 10, 19],
        [14, 22, 24, 30, 16, 19]],

       [[ 4, 27,  4,  4, 17,  2],
        [29, 17,  2, 29,  8, 11],
        [17, 28, 13, 15, 29, 20],
        [28,  7,  9, 16, 28, 19]]])

In [38]:
np.array([5.0, 4.2, 8.2])

array([5. , 4.2, 8.2])

In [39]:
x = np.array([3,4,2.4])
x[1]

4.0

In [40]:
np.array([True,3,False])

array([1, 3, 0])

In [41]:
x.astype(np.int32)

array([3, 4, 2])

### Filtrando Arrays

In [42]:
arr1 = np.array([1, 2, 3, 4, 5])
mask = arr1 % 3 == 0
mask

array([False, False,  True, False, False])

In [43]:
pessoas_id_idade = np.array([[1,22],[2,21],[3,27],[4,26]]) 
pessoas_id_idade  

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

In [44]:
mask_maior21 = pessoas_id_idade[:, 1] > 21
pessoas_id_idade[mask_maior21]

array([[ 1, 22],
       [ 3, 27],
       [ 4, 26]])

In [45]:
np.where(mask_maior21)

(array([0, 2, 3], dtype=int64),)

- Usando um index booleano crie um array que contém os dados da maior espécie encontrada(considerando seu tamanho), esse valor corresponde ao valor 22

- Usando fency index faça um array que contém apenas dados da espécie ID 297
- usando np.where faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados
- considere a profundeza em que o espécie foi encontrada, substitua valores maiores que 60 com "profundo"



In [46]:
especies = np.array([[747,  89,  33,  5],
                    [623,  123,  32,  13],
                    [501,  22,  49,  2],
                    [116,  101,  42,  10],
                    [297,  56,   69,   22],
                    [613,  64,  27,  7],
                    [295,  84,   29,   14],
                    [692,  105,   72,  16],
                    [229,  103,  35,  5],
                    [374,  124,  70,  1]])

especies
                 

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [47]:
maior_especie = especies[especies[:, 3] == 22]
maior_especie

array([[297,  56,  69,  22]])

In [48]:
mask_297 = especies[:, 0] == 297
especies[mask_297]


array([[297,  56,  69,  22]])

In [49]:
np.where(especies[:, 1] == 105)

(array([7], dtype=int64),)

In [50]:
especies[np.where(especies[:, 1] == 105)]

array([[692, 105,  72,  16]])

In [51]:
especies[:, 2] > 60

array([False, False, False, False,  True, False, False,  True, False,
        True])

In [52]:
np.where(especies[:, 2] > 60, "Profundo", especies[:,2])

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U11')

##### Salvando arrays em arquivos

In [53]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]]) 
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr3d.shape

np.savetxt('arr2d.csv', arr2d, delimiter=',')